/**
 * Shell Tab Completion Generation Module
 *
 * Generates shell completion scripts for bash, zsh, and fish.
 * Inspired by Aider's --shell-completions feature.
 *
 * This capability improves CLI usability by enabling tab completion
 * for commands, options, and file paths.
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

// Types
export interface ShellCompletionConfig {
	enabled: boolean;
	shell: "bash" | "zsh" | "fish" | "auto";
	installDir?: string;
	commandName: string;
}

export interface ShellCompletionStats {
	generations: number;
	installations: number;
	byShell: Record<string, number>;
	lastGenerationTime: string;
}

export interface CompletionCommand {
	name: string;
	description: string;
	options?: CompletionOption[];
	subcommands?: CompletionCommand[];
}

export interface CompletionOption {
	name: string;
	shortName?: string;
	description: string;
	argHint?: string;
}

// Default configuration
const DEFAULT_CONFIG: ShellCompletionConfig = {
	enabled: true,
	shell: "auto",
	commandName: "evo",
};

// Sample commands and options for evo CLI
const EVO_COMMANDS: CompletionCommand[] = [
	{
		name: "evo",
		description: "Self-evolving AI agent",
		options: [
			{ name: "help", shortName: "h", description: "Show help" },
			{ name: "version", shortName: "v", description: "Show version" },
			{ name: "model", description: "LLM model to use", argHint: "MODEL" },
			{ name: "api-key", description: "API key for the model", argHint: "KEY" },
			{ name: "base-url", description: "API base URL", argHint: "URL" },
			{ name: "max-iterations", description: "Maximum iterations", argHint: "N" },
			{ name: "config", description: "Config file path", argHint: "FILE" },
			{ name: "skill", description: "Skill to use", argHint: "SKILL" },
			{ name: "verbose", description: "Enable verbose logging" },
			{ name: "dry-run", description: "Dry run mode" },
		],
	},
];

let generatorInstance: ShellCompletionGenerator | null = null;

export class ShellCompletionGenerator {
	private config: ShellCompletionConfig;
	private stats: ShellCompletionStats;
	private dataPath: string;

	constructor(config?: Partial<ShellCompletionConfig>) {
		this.config = { ...DEFAULT_CONFIG, ...config };
		this.dataPath = path.join(os.homedir(), ".paimon", "shell-completion.json");
		this.stats = {
			generations: 0,
			installations: 0,
			byShell: { bash: 0, zsh: 0, fish: 0 },
			lastGenerationTime: "",
		};
		this.loadData();
		this.detectShell();
	}

	private loadData(): void {
		try {
			if (fs.existsSync(this.dataPath)) {
				const data = JSON.parse(fs.readFileSync(this.dataPath, "utf-8"));
				this.stats = data.stats || this.stats;
				this.config = { ...this.config, ...data.config };
			}
		} catch {
			// Start fresh
		}
	}

	private saveData(): void {
		try {
			const dir = path.dirname(this.dataPath);
			if (!fs.existsSync(dir)) {
				fs.mkdirSync(dir, { recursive: true });
			}
			fs.writeFileSync(
				this.dataPath,
				JSON.stringify({ stats: this.stats, config: this.config }, null, 2),
			);
		} catch (error) {
			console.error("Failed to save shell completion data:", error);
		}
	}

	private detectShell(): void {
		if (this.config.shell !== "auto") return;

		const shell = process.env.SHELL || "";
		if (shell.includes("zsh")) {
			this.config.shell = "zsh";
		} else if (shell.includes("fish")) {
			this.config.shell = "fish";
		} else {
			this.config.shell = "bash";
		}
	}

	public getConfig(): ShellCompletionConfig {
		return { ...this.config };
	}

	public updateConfig(updates: Partial<ShellCompletionConfig>): void {
		this.config = { ...this.config, ...updates };
		this.saveData();
	}

	public getStats(): ShellCompletionStats {
		return { ...this.stats };
	}

	/**
	 * Generate bash completion script
	 */
	public generateBashCompletion(commands: CompletionCommand[] = EVO_COMMANDS): string {
		const cmd = commands[0];
		if (!cmd) return "";

		const script = `# Bash completion for ${this.config.commandName}
# Generated by ${this.config.commandName} shell-completion tool
# Install: source <(${this.config.commandName} shell-completion bash)
# Or add to ~/.bashrc: eval "$(${this.config.commandName} shell-completion bash)"

_${this.config.commandName}_completion() {
    local cur prev words cword
    _init_completion || return

    # Options
    local options="${cmd.options?.map((o) => (o.shortName ? `-${o.shortName} --${o.name}` : `--${o.name}`)).join(" ") || ""}"

    # If completing an option
    if [[ \${cur} == -* ]]; then
        COMPREPLY=($(compgen -W "\${options}" -- "\${cur}"))
        return
    fi

    # If previous word is an option that takes an argument
    case \${prev} in
        --model|-m)
            COMPREPLY=($(compgen -W "claude-sonnet claude-opus gpt-4o gpt-4-turbo deepseek-r1 o1 o3-mini" -- "\${cur}"))
            return
            ;;
        --skill|-s)
            COMPREPLY=($(compgen -W "evolve research self-improve explore-code plan-architecture review-changes" -- "\${cur}"))
            return
            ;;
        --config|-c|--api-key|-k|--base-url|-u)
            _filedir
            return
            ;;
    esac

    # Default: file completion
    _filedir
}

complete -F _${this.config.commandName}_completion ${this.config.commandName}
`;

		this.stats.generations++;
		this.stats.byShell.bash++;
		this.stats.lastGenerationTime = new Date().toISOString();
		this.saveData();

		return script;
	}

	/**
	 * Generate zsh completion script
	 */
	public generateZshCompletion(commands: CompletionCommand[] = EVO_COMMANDS): string {
		const cmd = commands[0];
		if (!cmd) return "";

		const options = cmd.options || [];
		const optionsStr = options
			.map((o) => {
				const opts = o.shortName ? `-${o.shortName}` : "";
				const optl = `--${o.name}`;
				const desc = o.description.replace(/'/g, "'\\''");
				if (o.argHint) {
					return `'${opts}[${desc}]:${o.argHint}' '${optl}[${desc}]:${o.argHint}'`;
				}
				return `'${opts}[${desc}]' '${optl}[${desc}]'`;
			})
			.join("\n        ");

		const script = `#compdef ${this.config.commandName}
# Zsh completion for ${this.config.commandName}
# Generated by ${this.config.commandName} shell-completion tool
# Install: source <(${this.config.commandName} shell-completion zsh)
# Or add to ~/.zshrc: eval "$(${this.config.commandName} shell-completion zsh)"

_${this.config.commandName}() {
    local -a commands
    local -a options

    options=(
        ${optionsStr}
    )

    _arguments -C -s \\
        $options \\
        '1: :->cmd' \\
        '*: :->args'

    case $state in
        cmd)
            _describe 'command' commands
            ;;
        args)
            case $words[2] in
                --model|-m)
                    _describe 'model' 'claude-sonnet claude-opus gpt-4o gpt-4-turbo deepseek-r1 o1 o3-mini'
                    ;;
                --skill|-s)
                    _describe 'skill' 'evolve research self-improve explore-code plan-architecture review-changes'
                    ;;
                *)
                    _files
                    ;;
            esac
            ;;
    esac
}

_${this.config.commandName}
`;

		this.stats.generations++;
		this.stats.byShell.zsh++;
		this.stats.lastGenerationTime = new Date().toISOString();
		this.saveData();

		return script;
	}

	/**
	 * Generate fish completion script
	 */
	public generateFishCompletion(commands: CompletionCommand[] = EVO_COMMANDS): string {
		const cmd = commands[0];
		if (!cmd) return "";

		const options = cmd.options || [];
		const optionsStr = options
			.map((o) => {
				const optl = `-l ${o.name}`;
				const opts = o.shortName ? `-s ${o.shortName}` : "";
				const desc = o.description.replace(/'/g, "\\'");
				if (o.argHint) {
					return `complete -c ${this.config.commandName} ${opts} ${optl} -d '${desc}' -r`;
				}
				return `complete -c ${this.config.commandName} ${opts} ${optl} -d '${desc}'`;
			})
			.join("\n");

		const script = `# Fish completion for ${this.config.commandName}
# Generated by ${this.config.commandName} shell-completion tool
# Install: ${this.config.commandName} shell-completion fish | source
# Or save to ~/.config/fish/completions/${this.config.commandName}.fish

# Options
${optionsStr}

# Model completions
complete -c ${this.config.commandName} -l model -d 'LLM model to use' -xa 'claude-sonnet\tClaude 3.5 Sonnet claude-opus\tClaude 3 Opus gpt-4o\tGPT-4o gpt-4-turbo\tGPT-4 Turbo deepseek-r1\tDeepSeek R1 o1\tOpenAI o1 o3-mini\tOpenAI o3-mini'

# Skill completions
complete -c ${this.config.commandName} -l skill -d 'Skill to use' -xa 'evolve\tSelf-evolution workflow research\tWeb/documentation search self-improve\tSelf-improvement guidelines explore-code\tDeep codebase exploration plan-architecture\tArchitecture planning review-changes\tCode review'

# File completions
complete -c ${this.config.commandName} -l config -d 'Config file path' -r -F
`;

		this.stats.generations++;
		this.stats.byShell.fish++;
		this.stats.lastGenerationTime = new Date().toISOString();
		this.saveData();

		return script;
	}

	/**
	 * Generate completion script for the specified shell
	 */
	public generate(shell?: "bash" | "zsh" | "fish"): string {
		let targetShell = shell || this.config.shell;
		if (targetShell === "auto") {
			this.detectShell();
			targetShell = this.config.shell as "bash" | "zsh" | "fish";
		}

		switch (targetShell) {
			case "bash":
				return this.generateBashCompletion();
			case "zsh":
				return this.generateZshCompletion();
			case "fish":
				return this.generateFishCompletion();
			default:
				throw new Error(`Unsupported shell: ${targetShell}`);
		}
	}

	/**
	 * Install completion script
	 */
	public install(shell?: "bash" | "zsh" | "fish"): {
		success: boolean;
		path: string;
		message: string;
	} {
		let targetShell = shell || this.config.shell;
		if (targetShell === "auto") {
			this.detectShell();
			targetShell = this.config.shell as "bash" | "zsh" | "fish";
		}

		const script = this.generate(targetShell);
		let installPath: string;

		const home = os.homedir();

		switch (targetShell) {
			case "bash":
				installPath = path.join(
					home,
					".local",
					"share",
					"bash-completion",
					"completions",
					this.config.commandName,
				);
				break;
			case "zsh":
				installPath = path.join(home, ".zsh", "completions", `_${this.config.commandName}`);
				break;
			case "fish":
				installPath = path.join(
					home,
					".config",
					"fish",
					"completions",
					`${this.config.commandName}.fish`,
				);
				break;
			default:
				throw new Error(`Unsupported shell: ${targetShell}`);
		}

		try {
			const dir = path.dirname(installPath);
			if (!fs.existsSync(dir)) {
				fs.mkdirSync(dir, { recursive: true });
			}
			fs.writeFileSync(installPath, script);

			this.stats.installations++;
			this.saveData();

			return {
				success: true,
				path: installPath,
				message: `Completion script installed to ${installPath}. You may need to restart your shell or source the file.`,
			};
		} catch (error) {
			const errorMsg = error instanceof Error ? error.message : String(error);
			return {
				success: false,
				path: installPath,
				message: `Failed to install completion script: ${errorMsg}`,
			};
		}
	}

	/**
	 * Get installation instructions
	 */
	public getInstallInstructions(shell?: "bash" | "zsh" | "fish"): string {
		let targetShell = shell || this.config.shell;
		if (targetShell === "auto") {
			this.detectShell();
			targetShell = this.config.shell;
		}

		const cmd = this.config.commandName;

		switch (targetShell) {
			case "bash":
				return `# Bash Installation Instructions

## Option 1: One-time source
source <(${cmd} shell-completion bash)

## Option 2: Add to ~/.bashrc
echo 'eval "$(${cmd} shell-completion bash)"' >> ~/.bashrc

## Option 3: Install to system directory
${cmd} shell-completion install bash
# Then add to ~/.bashrc:
# source ~/.local/share/bash-completion/completions/${cmd}
`;

			case "zsh":
				return `# Zsh Installation Instructions

## Option 1: One-time source
source <(${cmd} shell-completion zsh)

## Option 2: Add to ~/.zshrc
echo 'eval "$(${cmd} shell-completion zsh)"' >> ~/.zshrc

## Option 3: Install to completions directory
${cmd} shell-completion install zsh
# Add to ~/.zshrc:
# fpath=(~/.zsh/completions $fpath)
# autoload -U compinit && compinit
`;

			case "fish":
				return `# Fish Installation Instructions

## Option 1: One-time source
${cmd} shell-completion fish | source

## Option 2: Install to completions directory
${cmd} shell-completion install fish
# Fish will automatically load completions from ~/.config/fish/completions/
`;

			default:
				return "Unknown shell. Supported shells: bash, zsh, fish";
		}
	}

	public isEnabled(): boolean {
		return this.config.enabled;
	}

	public setEnabled(enabled: boolean): void {
		this.config.enabled = enabled;
		this.saveData();
	}

	public reset(): void {
		this.stats = {
			generations: 0,
			installations: 0,
			byShell: { bash: 0, zsh: 0, fish: 0 },
			lastGenerationTime: "",
		};
		this.config = { ...DEFAULT_CONFIG };
		this.saveData();
	}
}

// Singleton access
export function getShellCompletionGenerator(): ShellCompletionGenerator {
	if (!generatorInstance) {
		generatorInstance = new ShellCompletionGenerator();
	}
	return generatorInstance;
}

export function resetShellCompletionGenerator(): void {
	generatorInstance = null;
}
